services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=gymsession'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - '/path/to/shared/volume:/var/lib/postgresql/data'