spring.application.name=gymsession
spring.datasource.url=jdbc:postgresql://localhost:5432/gymsession
spring.datasource.username=admin
spring.datasource.password=admin

# Security configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/develop
jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

# JWT configuration
gymsession.app.jwtSecret= ======================GYMSESSIONASECRET===========================
gymsession.app.jwtExpirationMs=86400000
gymsession.app.jwtCookieName=gymsession

# JWT Auth Converter configuration
jwt.auth.converter.principle-attribute=preferred_username
jwt.auth.converter.resource-id=gymsession

# Server configuration
server.port=8081

# Keycloak configuration
keycloak.credentials.secret=PLACEHOLDER